### ISSUE TITLE
Bug: controller not placed at the correct file system location

### ISSUE THREAD

**Issue by wuuti** [degoya/degoyaActionButton#4] opened 2015-10-02 13:32 UTC
The controller is not placed correctly by the installer:

![screenshot from 2015-10-02 15 32 00](https://cloud.githubusercontent.com/assets/2852461/10247648/c07e6e9c-691a-11e5-8ae2-4c638fb33739.png)

This is a serious bug... imho the controller should be inside assets/components/degoyaActionButton

**Comment by wuuti** [comment] 2015-10-02 13:51
Update: the component itself also does not install in the right core-folder: if you have renamed the core folder, it still installs itself to /core/components/.
Update: only the elements are installed to that location:

![screenshot from 2015-10-02 15 55 36](https://cloud.githubusercontent.com/assets/2852461/10248141/0953f9b8-691e-11e5-9199-0b57a5254c7c.png)

The rest (_and_ again the elements) are installed correctly under the custom core path.

**Comment by degoya** [comment] 2015-10-03 16:46
was caused by static elements. fixed in beta9 transport

**Closed as completed by degoya** 2015-10-03 16:46 UTC
